# Generated by Django 3.0.2 on 2020-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
    ]
