# Generated by Django 3.0.2 on 2020-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_username',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
    ]
