# Generated by Django 3.0.2 on 2020-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200119_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.CharField(default='https://cube.elemecdn.com/3/7c/3ea6beec64369c2642b92c6726f1epng.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_username',
            field=models.CharField(default='None', max_length=30, null=True),
        ),
    ]
